### ISSUE TITLE
ViT related questions

### ISSUE THREAD

**Issue by Asaad-Pak** [Omid-Nejati/MedViT#19]
Which ViT was used as starting point? Was it ViT-B/16 or ViT-B/32? The checkpoints you provided in the readme file there you have written MedViT trained on ImageNet1k dataset. Wasn't MedViT was supposed to be trained on some medical dataset? @Omid-Nejati @kashiani  Your help will be greatly appreciated

**Comment by kashiani** [comment]
MedViT builds are based on of [RVT ](https://github.com/vtddggg/Robust-Vision-Transformer)and [LocalViT](https://github.com/ofsoundof/LocalViT), as outlined in the README. Each MedViT variant (MedViT-T, MedViT-S, MedViT-L) can be trained using the MedViT_small, MedViT_base, and MedViT_large modules via the provided `colab_MedViT.ipynb` notebook.

Furthermore, the pretrained weights and results currently available are based on pretraining with the ImageNet-1K dataset. In response to multiple requests for custom dataset training, we have pretrained MedViT on ImageNet-1K and released the associated weights.
