### ISSUE TITLE
Request for the implementation and training code of the comparative resnet

### ISSUE THREAD

**Issue by MeycL** [Omid-Nejati/MedViT#2]
Thank you very much for your wonderful work MedViT, if possible, could you please open source the implementation and training code of the comparative resnet? Your work is very much appreciated.

**Comment by Omid-Nejati** [comment]
The implementation of the comparative ResNet can be easily applied to our code by making changes to the model line.

from MedViT import MedViT_small as tiny   >>>>>>>  model = timm.create_model('resnet50', num_classes=10)
