### ISSUE TITLE
PMC

### ISSUE THREAD

**Issue by 10532** [Omid-Nejati/MedViT#3]
The paper mentions the PMC module will be used after stage 1, but it is not reflected in the provided code.Can you provide the code related to the PMC module

**Comment by Omid-Nejati** [comment]
Apologies for the delayed response. The PMC module is actually a component of MedViT*, and it's part of the ablation study for our work, not the original MedViT. We're currently preparing a paper on data augmentation in transformers, and it will include a comprehensive explanation of it. However, if you're interested in obtaining it sooner, please feel free to email me.
