### ISSUE TITLE
Error while running the code

### ISSUE THREAD

**Issue by Junaid199f** [Omid-Nejati/MedViT#4]
Hi! While running the notebook the following error occurs. Could you please assist me to solve this problem. Thanks

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-18-9e415831e5cc> in <cell line: 3>()
     21             loss = criterion(outputs, targets)
     22 
---> 23         loss.backward()
     24         optimizer.step()

2 frames
/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py in _make_grads(outputs, grads, is_grads_batched)
    125                     raise RuntimeError(msg)
    126                 new_grads.append(
--> 127                     torch.ones_like(out, memory_format=torch.preserve_format)
    128                 )
    129             else:

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by Omid-Nejati** [comment]
Hi, we have updated the colab code and installation requirements.
